default: &default
  adapter: mysql2
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: redrock_dev

test:
  <<: *default
  database: redrock_test

production:
  <<: *default
  database: redrock_production
